### ISSUE TITLE
Error on install: 

### ISSUE THREAD

**Issue by rickcecil** [mikwielgus/forum-dl#11]
When I try installing from pip, I get the following error:

```
ERROR: Could not find a version that satisfies the requirement forum-dl (from versions: none)
ERROR: No matching distribution found for forum-dl
```

When I try to install from a local clone, I get the following error:

```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /path/to/forum-dl
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

For pip, I've tried pip and pip3. I generally need to use pip3 to install things from pip for python3. I get the same error using both commands.

Results of uname -a
```
Linux computername 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

cat /etc/os-release
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

pip3 --version
```
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

Thanks for any help. And let me know if you need any additional data.

**Comment by rickcecil** [comment]
After some experimentation, it looks like you need python 3.10.11. I switched to this version and was able to complete the install.

**Comment by mikwielgus** [comment]
Yeah, I should state it more prominently which Python versions are supported. I can try to lower the minimum version, if I recall correctly the primary blocker was merely some type annotation features.

**Comment by mikwielgus** [comment]
Added some badges to the readme in 50a99204e1eed4ac707dca1dcff64d396f1e5cee.
