### ISSUE TITLE
maildir only outputs 1 empty file

### ISSUE THREAD

**Issue by peterjschroeder** [mikwielgus/forum-dl#2]
On phpbb forums; when selecting maildir as the file format, only a single blank file is created in cur.

**Comment by mikwielgus** [comment]
Thanks for the report.

In formats that allow having subdirectories (Maildir and Babyl), each board is stored in its own subdirectory. You should be able to find your messages there (note that in Maildir, each of subdirectories starts with an ".", so by default they're hidden).

I checked just now and for some reason `neomutt` doesn't show these subdirectories for me unless pointed to only one of them directly.  Not sure whether it's a problem with `forum-dl` or with my Neomutt configuration.

**Comment by peterjschroeder** [comment]
Found the folder, thank you. From what I've seen mutt is picky about folder names, so that doesn't surprise me.
